config/routes.rb
Rails.application.routes.draw do
  resources :lists do
    resources :steps
  end

  get 'welcome/index'

  root 'welcome#index'

end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :steps, dependent: :destroy

  validates :title, presence: true, length: { minimum: 4}

end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :list

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      flash[:notice] = 'List was successfully created.'
      redirect_to @list
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @list.update(list_params)
      flash[:notice] = "List was successfully updated."
      redirect_to @list
    else
      flash[:error] = "Error updating List, please try again."
      render :edit
    end
  end

  def destroy
    @list.destroy
    flash[:notice] = 'List was successfully deleted.'
    redirect_to lists_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:title)
  end

end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :set_list
  before_action :set_step, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @step = Step.new
  end

  def create
    @step = @list.steps.new(step_params)
    if @step.save
      flash[:notice] = "Step created successfully"
      redirect_to @list
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @step.update(step_params)
      flash[:notice] = "Step updated successfully"
      redirect_to [@list, @step]
    else
      render :edit
    end
  end

  def destroy
    @step.destroy
    redirect_to @list
  end



  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_step
    @step = Step.find(params[:id])
  end

  def step_params
    params.require(:step).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HowToLists</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit' %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Now Editing: <%= @list.title %></h1>
<%= link_to 'Back to List', list_path %><br>

<p><%= render 'form' %></p>

app/views/lists/index.html.erb
<h1>How-To List Index</h1>

<% @lists.each do |list| %>
  <div>
    - <%= list.title %> -
    <%= link_to "Show", list %>
    <%= link_to "Edit", edit_list_path(list) %> |
    <%= link_to "Delete", list, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
<% end %>
<br>
<div>
  ______________________
<p>
  <%= link_to 'Home', welcome_index_path %> |
  <%= link_to 'New How-To List', new_list_path %>
</p>

app/views/lists/new.html.erb
<h1>Create New How-To List</h1>
<%= link_to 'Back to How-To List Index', lists_path %><br>

<p><%= render 'form' %></p>

app/views/lists/show.html.erb
<h1>List: <%= @list.title %></h1>
<h2>Steps:</h2>
<ul>
  <% @list.steps.each do |step| %>
  <li><%= step.name %> -
    <%= link_to 'Show', list_step_path(@list, step) %> |
    <%= link_to 'Edit', edit_list_step_path(@list, step) %> |
    <%= link_to 'Delete', list_step_path(@list, step), method: :delete, data: { confirm: 'Are you sure?'} %>
  </li>
  <% end %>
</ul>
<p><%= link_to 'Create a Step', new_list_step_path(@list) %></p>

<%= link_to 'Back to List Index', lists_path %> |
 |
<%= link_to "Edit List Title", edit_list_path %> |
<%= link_to "Delete this List", @list, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/steps/_form.html.erb
<%= form_for [@list, @step] do |f| %>
  <% if @step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@step.errors.count, "error") %> prohibited this step from being saved:</h2>

      <ul>
      <% @step.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit 'Submit' %>
  </div>
<% end %>

app/views/steps/edit.html.erb
<h1>Now Editing Step: <%= @step.name %></h1>

<%= render 'form' %>

app/views/steps/new.html.erb
<h1>Create a new Step:</h1>

<%= render 'form' %>
<br>

<%= link_to 'Back to List', list_path(@list) %>

app/views/steps/show.html.erb
<h1> Showing Step: <%= @step.name %></h1>
<%= link_to 'Back to List', @list %> |
<%= link_to 'Delete This Step', [@list, @step], method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/welcome/index.html.erb
<h1>Create How-To Lists Today.</h1>
<p><%= link_to 'How-To List Index', lists_path %></p>
<p><%= link_to 'Creat a New How-To', new_list_path %></p>